name: docup
description: docup project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.4+5

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  sliding_up_panel: ^1.0.2
  polygon_clipper: ^1.0.2
  google_maps_flutter: ^0.5.24+1
  http: ^0.12.0+4
  shadow: ^0.1.5
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^0.2.0
  icon_shadow: ^1.0.1
  progress_dialog: ^1.2.1
  dashed_container: ">=1.0.1"
  shared_preferences: ^0.5.6+3
  image_picker: ">=0.6.4"
  agora_rtc_engine: ^1.0.5
  permission_handler: ^3.0.0
  device_info: ^0.4.2+1
  flutter_local_notifications: ^1.4.1
  intl: ^0.16.1
  dio: ">=3.0.0"
  percent_indicator: ^2.1.3
  persian_datetime_picker: ^1.0.5
  shamsi_date: ^0.7.0
  jaguar_jwt: ^2.1.6
  firebase_messaging: ^6.0.8
  datetime_picker_formfield: ^1.0.0
  #  introduction_screen: ^1.0.7
  flutter_launcher_icons: ">=0.6.1"
  url_launcher: ^5.4.5
  searchable_dropdown: ^1.1.3
  flutter_rating_bar: ^3.0.1+1
  firebase_crashlytics: ^0.1.3
  web_socket_channel: ^1.1.0
  uni_links: ^0.4.0
  photo_view: ^0.9.2
  keyboard_visibility: ^0.5.6
  simple_tooltip: ^0.1.10
  loadmore: ^1.0.4
  flutter_circular_slider: ^2.5.0
  auto_size_text: ^2.1.0
  flutter_credit_card: ^0.1.3


flutter_icons:
  image_path: "assets/logoRec.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/noronioClinic/
    - assets/home/
    - assets/account/
    - assets/panel/
    - assets/startPage/
    - assets/visitLists/




  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: iransans
      fonts:
        - asset: assets/IRANSans.ttf
